//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroAlmacen
    {
        public decimal IdRegistro { get; set; }
        public decimal IdSucursal { get; set; }
        public decimal IdProducto { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
